modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/NukelordPvP/Blood-N-Wine-2-Resources/issues"
[[mods]]
modId="bloodnwine2resources"
version="${file.jarVersion}"
displayName="Blood N Wine 2 Resources"
# A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://github.com/NukelordPvP/Blood-N-Wine-2-Resources"
logoFile="bloodnwine2resources.png"
credits="Steve3, Lord_Mahan and Nukelord420"
authors="Nukelord420"

# The description text for the mod (multi line!)
description='''
Blood N Wine 2 Resources used to fix bugs in blood n wine 2
'''
[[dependencies.bloodnwine2resources]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
[[dependencies.bloodnwine2resources]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
